[package]
name = "sir_logger"
version = "0.1.0"
edition = "2024"

[dependencies]
fern = { version = "^0.6", features = ["colored"] }
humantime = "^2.1.0"
log = "^0.4.0"

[features]
no-panic-handler = []
